CREATE USER IF NOT EXISTS 'AionChile2025'@'%' IDENTIFIED BY 'AionChile';
GRANT ALL PRIVILEGES ON aion_ls.* TO 'AionChile2025'@'%';
GRANT ALL PRIVILEGES ON aion_gs.* TO 'AionChile2025'@'%';
GRANT ALL PRIVILEGES ON aion_cs.* TO 'AionChile2025'@'%';
FLUSH PRIVILEGES;